const Map<String, String> en = {
  // Bottom Nav Bar
  'txt_bottomnav_discover': 'Discover',
  'txt_bottomnav_setting': 'Setting',
  'txt_bottomnav_past_ticket': 'Past Ticket',

  // Login
  'txt_flow_login_welcome': "Let's get Started 🙌",
  'txt_flow_login_sign_in': 'Sign in into your Account',
  'txt_flow_login_email': 'Email',
  'txt_flow_login_enter_email': 'input email',
  'txt_flow_login_password': 'Password',
  'txt_flow_login_enter_password': 'input password',
  'txt_flow_login_language': 'Language',
  'txt_flow_login_change_language': 'Change Language',
  'txt_flow_login_forgot_password': 'Forgot Password?',
  'txt_flow_login_login': 'Login',
  'txt_flow_login_indonesian': 'Indonesian',
  'txt_flow_login_english': 'English',
  'txt_flow_login_save': 'Save',

  // Forgot Pass
  'txt_flow_forgotpass_back': 'Back',
  'txt_flow_forgotpass_title': 'Password Recovery ❤️‍🩹',
  'txt_flow_forgotpass_instructions': 'Stay relaxed! Please enter the email address associated with your registration, and we\'ll send you a verification code promptly.',
  'txt_flow_forgotpass_email': 'Email',
  'txt_flow_forgotpass_input_email': 'input email',
  'txt_flow_forgotpass_send_code': 'Send Code',
  'txt_flow_forgotpass_check_email': 'Check your Email Box!',
  'txt_flow_forgotpass_sent_code': 'We have sent a code to',
  'txt_flow_forgotpass_enter_code': 'Please enter the 4-digit code that was provided to you.',
  'txt_flow_forgotpass_resend_code': 'Resend Code',
  'txt_flow_forgotpass_verification': 'Verification',
  'txt_flow_forgotpass_create_password': 'Create a new password',
  'txt_flow_forgotpass_password_instructions': 'Please ensure that you remember your new password for future use. 😃',
  'txt_flow_forgotpass_input_new_password': 'Input New Password',
  'txt_flow_forgotpass_enter_password': 'input password',
  'txt_flow_forgotpass_reenter_new_password': 'Re-enter New Password',
  'txt_flow_forgotpass_reenter_password': 're-enter password',
  'txt_flow_forgotpass_password_min_chars': 'Minimum 8 characters',
  'txt_flow_forgotpass_reset_password': 'Reset Password',
  'txt_flow_forgotpass_password_changed': 'Your password has been successfully updated.',
  'txt_flow_forgotpass_return_to_login': 'Return to Login Menu',

  // Logout
  'txt_flow_logout_resources': 'Resources',
  'txt_flow_logout_rate_app': 'Rate this App on',
  'txt_flow_logout_contact_us': 'Contact Us',
  'txt_flow_logout_log_out': 'Log Out',
  'txt_flow_logout_confirmation': 'Confirmation',
  'txt_flow_logout_confirm_logout': 'Are you sure to logout?',
  'txt_flow_logout_yes_logout': 'Yes, Logout',
  'txt_flow_logout_cancel': 'Cancel',

  // Validator
  'txt_validator_required': 'This section must not be empty',
  'txt_validator_valid_email': 'Enter a valid email',
  'txt_validator_password_length': 'Password must be at least 8 characters',
  'txt_validator_valid_year': 'Enter a valid year',
  'txt_validator_greater_than_or_equal': 'Value must be greater than or equal to',
  'txt_validator_less_than_or_equal': 'Value must be less than or equal to',
  'txt_validator_numbers_only': 'This section must be filled with numbers',
};
